

name: teste ci cypress

on:
  push:
    branches: [ "main" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    uses: actions/checkout@v4
    name: Use Node.js 
    uses: actions/setup-node@v4
    with:
        node-version: 18
        cache: 'npm'
    -name: Instalar Dependencias 
    run: npm install

    -name: Executar teste
    run: npm test 
  
